### ISSUE TITLE
Question about Fauna's graphql endpoint

### ISSUE THREAD

**Issue by tatimblin** [NickyMeuleman/serverless-graphql#3]
Hey @NickyMeuleman I was following along with the articles, and am curious why you didn't use Fauna's built-in [gql endpoint](https://docs.fauna.com/fauna/current/api/graphql/endpoints). Can you share some about this choice? Loved the articles btw!

**Comment by NickyMeuleman** [comment]
You definitely can!
Started the articles as a way to set up your own serverless GraphQL endpoint and arrived at the FaunaDB choice to store data later. (Fauna is one option to do that, I tried to keep the option to choose another database provider open.)

Consuming their GraphQL-API inside our own resolvers, while possible with little effort, would quickly become confusing for the purpose of the article.
(Alternatively you could skip the whole own serverless GraphQL endpoint we made in the articles and use Fauna's directly)

PS: It also gave me a good excuse to learn more about their FQL, which is fascinating.
Thanks so much, glad you enjoyed them!

**Comment by tatimblin** [comment]
Awesome thanks for the explanation!
